alert("Здраствуйте, сейчас я задам пару вопросов.")
let x = prompt ("Как вас зовут ?")
alert(" Меня зовут BOT. Приятно познакомится! " + x)
console.log(x)
let q = prompt ("Укажите свой пол.")
alert("Ок. " + q) 
console.log(q)
let z = prompt ("Сколько вам лет ?")
alert(" Круто, а мне...забыл)")
console.log(z)
let с = prompt ("Укажите дату и место рождения")
alert("Ок. " + с) 
console.log(с)
let r = prompt (" Укажите адрес фактического проживания и место постоянной регистрации.")
alert("Ок. " + r) 
console.log(r)
let b = prompt ("Какое у вас образование?" )
alert(" Супер!!!" + b)
console.log(b)
let w = prompt ("Чем вы увликаетесь? (хоби)")
alert("Круто! " + w) 
console.log(w)
let t = prompt ("Есть судимость или проблемы с законом?")
alert("ок.. " + t) 
console.log(t)
let y = prompt ("На какую зарплату вы рассчитываете?")
alert("Ок. " + y) 
console.log(y)
let v = prompt ("Пожалуйста, оставте ваш телефон, чтобы мы могли с вами связаться)")
alert(" Спасибо большое, удачи! С уважениям BOT.")
console.log(v)